name: Build and Release to Docker

on:
  push:
    branches:
      - release # Triggers on pushes to the release branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Update to the .NET version your project uses

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Build the application
    - name: Build Application
      run: dotnet build --configuration Release --no-restore

    # Run tests
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    # Build Docker Image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Tag Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/aspnet-web-api:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/aspnet-web-api:latest ${{ secrets.DOCKER_USERNAME }}/aspnet-web-api:${{ github.run_number }}

    # Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/aspnet-web-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/aspnet-web-api:${{ github.run_number }}
